# Generated by Django 6.0.1 on 2026-02-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(default='Мирослав', max_length=35, verbose_name='Введите имя человека')),
                ('tour', models.CharField(default='.... тур', max_length=70, verbose_name='Введите название тура')),
            ],
        ),
        migrations.CreateModel(
            name='Touring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_inn', models.CharField(default='0123456789', max_length=60, verbose_name='Введите паспорт или ИНН человека')),
                ('choice_tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choice_tour', to='relation_db.person')),
            ],
        ),
    ]
