# Generated by Django 6.0.1 on 2026-02-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='touring',
            name='passport_inn',
        ),
        migrations.AddField(
            model_name='person',
            name='passport_inn',
            field=models.CharField(default='0123456789', max_length=60, null=True, verbose_name='Введите паспорт или ИНН человека'),
        ),
        migrations.AddField(
            model_name='touring',
            name='tour',
            field=models.CharField(default='.... тур', max_length=70, null=True, verbose_name='Введите название тура'),
        ),
    ]
