# Generated by Django 6.0.1 on 2026-02-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0002_remove_person_tour_remove_touring_passport_inn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='passport_inn',
        ),
    ]
