# Generated by Django 6.0.1 on 2026-02-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0003_remove_person_passport_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=100)),
                ('comment', models.CharField(default='Хороший, не составил много проблем!', max_length=100)),
                ('choice_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_review', to='relation_db.person')),
            ],
        ),
    ]
