# Generated by Django 6.0.1 on 2026-02-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='kategory',
            field=models.ManyToManyField(null=True, to='relation_db.kategory'),
        ),
    ]
