# Generated by Django 6.0.1 on 2026-02-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0005_kategory_person_kategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='kategory',
            new_name='tags',
        ),
    ]
