# Generated by Django 6.0.1 on 2026-02-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0006_rename_kategory_person_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategory',
            new_name='Tag',
        ),
    ]
