# Generated by Django 6.0.1 on 2026-02-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0007_rename_kategory_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_category', models.CharField(max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='touring',
            name='choice_tour',
        ),
        migrations.RemoveField(
            model_name='person',
            name='people',
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='Владимир', max_length=35),
        ),
        migrations.AddField(
            model_name='person',
            name='tag_category',
            field=models.ManyToManyField(null=True, to='relation_db.category'),
        ),
        migrations.CreateModel(
            name='StarsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=100)),
                ('comments_stars', models.CharField(default='Хороший турист!', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_stars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_starts', to='relation_db.person')),
            ],
        ),
        migrations.CreateModel(
            name='Tourning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.CharField(default='.... тур!', max_length=60)),
                ('choice_tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choice_tour', to='relation_db.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Touring',
        ),
    ]
