# Generated by Django 6.0.1 on 2026-02-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0008_category_remove_person_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starsreview',
            name='choice_stars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='relation_db.person'),
        ),
        migrations.AlterField(
            model_name='tourning',
            name='choice_tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='relation_db.person'),
        ),
    ]
