# Generated by Django 6.0.1 on 2026-02-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='choice_tag',
        ),
    ]
