# Generated by Django 6.0.1 on 2026-01-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_books', models.CharField(max_length=100, verbose_name='Название книги')),
                ('quote_author', models.TextField(verbose_name='Цитата автора')),
                ('cover_image', models.ImageField(upload_to='books_covers/', verbose_name='Обложка книги')),
                ('documentation_books', models.FileField(blank=True, null=True, upload_to='books_docs/', verbose_name='Документация к книге')),
                ('url_books', models.URLField(blank=True, null=True, verbose_name='Ссылка на книгу')),
                ('email_author', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email автора')),
                ('author_books', models.TextField(verbose_name='Автор книги')),
                ('yootube_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube')),
                ('created_date_books', models.PositiveBigIntegerField(blank=True, verbose_name='Год издания')),
                ('created_at_message', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Цитата из книги',
                'verbose_name_plural': 'Цитаты из книг',
            },
        ),
    ]
